### ISSUE TITLE
Note su EPSG indicato nel README

### ISSUE THREAD

**Issue by aborruso** [pcm-dpc/DPC-Aggregati-Strutturali-ITG-Isole#4]
Buongiorno,
nel README in home si legge che per la Sicilia è usato `EPSG: 7792`.

Ho aperto l'shp di Palermo ed è `7794`.
Forse c'è da modificare qualcosa nel README.

Grazie

**Comment by pierluigicara** [comment]
Ciao @aborruso, è tutto ok. L'EPSG 7792 è quello originale attribuito dalla Regione Sicilia, l'EPSG 7794 invece è quello che abbiamo attribuito noi al dataset nazionale (fuso Italia) come suggerito da IGM (nel README trovi il link al documento che spiega tutto). Il dato che hai scaricato da qui non è dunque l'originale della Regione Sicilia ma un'estrazione per il comune di Palermo da quello che abbiamo derivato noi a livello nazionale. Grazie a te e saluti

**Comment by aborruso** [comment]
ciao @pierluigicara so che è ok, ma io aveva un po' confuso la prima lettura.

Visto che specificate che c'è un sistema originario, paleserei senza aprire link, che c'è un sistema di pubblicazione qui. Sotto solo un esempio di struttura.

Passare da

## Sistemi di riferimento dei dati originali

**SARDEGNA**

**Sistema Riferimento:** WGS_1984_UTM_Zone_32N

**EPSG:** 32632

**SICILIA**

**Sistema Riferimento:** RDN2008_UTM_zone_33N

**EPSG:** 7792

a

## Sistemi di riferimento 

### Originali

**SARDEGNA**

**Sistema Riferimento:** WGS_1984_UTM_Zone_32N

**EPSG:** 32632

**SICILIA**

**Sistema Riferimento:** RDN2008_UTM_zone_33N

**EPSG:** 7792

### Pubblicazione

**SARDEGNA**

**Sistema Riferimento:** WGS_1984_UTM_Zone_32N

**EPSG:** 32632

**SICILIA**

**Sistema Riferimento:** RDN2008 / Italy zone (E-N)

**EPSG:** 7794

**Comment by pierluigicara** [comment]
Capisco la tua difficoltà ma la distinzione esiste già nelle diverse descrizioni (dati originali e aggregati strutturali) e, inoltre, la cosa comporterebbe anche la ripetizione sugli altri 4 repository. Infine, la cosa riguarda tutte le regioni e non solo la Sicilia e quindi la tua aggiunta si dovrebbe ripetere, risultando alla fine solo ridondante. Spero che tu concordi con me 🙂
